name: Build and Deploy

on:
  push:
    branches:
      - main
  # pull_request: 
  #   branches:
  #     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm ci
          npm run build --prod -- --base-href=/recibos-pagos/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: www # The folder the action should deploy.

      - name: Create 404 page
        run: cp www/index.html www/404.html
